<a href="https://colab.research.google.com/github/vikassinngh123/AI-ML-Learning/blob/main/04-Pandas/03_StackOverflow_Survey_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df=pd.read_csv('/content/drive/MyDrive/survey_results_public.csv')
# df=pd.read_[different file type in place of csv]

/tmp/ipykernel_19275/3253665708.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/drive/MyDrive/survey_results_public.csv')

In [3]:
df.shape

(49191, 172)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [5]:
df.describe()

,ResponseId,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,...,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,49191.000000,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,...,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,24596.000000,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,...,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,14200.362883,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,...,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,12298.500000,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,...,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,24596.000000,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,...,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,36893.500000,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,...,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,49191.000000,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,...,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [6]:
# pd.set_option('display.max_columns',172)
# pd.set_option('display.max_row',172)

In [7]:
schema_df=pd.read_csv('/content/drive/MyDrive/survey_results_schema.csv')
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [8]:
pd.set_option('display.max_columns',11)
pd.set_option('display.max_row',11)

## Work exp V/s pay

In [9]:
from numpy._core.numeric import full
work_df=df.dropna(subset=["WorkExp","ConvertedCompYearly"])

world_work_df=work_df[(work_df["ConvertedCompYearly"]>1000) & (work_df["ConvertedCompYearly"]<1000000) & (work_df["WorkExp"]>0) & (work_df["WorkExp"]<30)]
cleaned_world_work_df=world_work_df[["WorkExp","ConvertedCompYearly"]]
cleaned_world_work_df=cleaned_world_work_df.groupby("WorkExp").agg({'ConvertedCompYearly':'mean'}).reset_index()
cleaned_world_work_df=cleaned_world_work_df.rename(columns={'ConvertedCompYearly':'World_AvgSalary'})

#USA
USA_work_df=work_df[(work_df["ConvertedCompYearly"]>1000) & (work_df["ConvertedCompYearly"]<1000000) & (work_df["WorkExp"]>0) & (work_df["WorkExp"]<30) & (work_df['Country'].isin(['United States of America']))]
cleaned_USA_work_df=USA_work_df[["WorkExp","ConvertedCompYearly"]]
cleaned_USA_work_df=cleaned_USA_work_df.groupby("WorkExp").agg({'ConvertedCompYearly':'mean'}).reset_index()
cleaned_USA_work_df=cleaned_USA_work_df.rename(columns={'ConvertedCompYearly':'USA_AvgSalary'})

#India
India_work_df=work_df[(work_df["ConvertedCompYearly"]>1000) & (work_df["ConvertedCompYearly"]<500000) & (work_df["WorkExp"]>0) & (work_df["WorkExp"]<30) & (work_df['Country'].isin(['India']))]
cleaned_India_work_df=India_work_df[["WorkExp","ConvertedCompYearly"]]
cleaned_India_work_df=cleaned_India_work_df.groupby("WorkExp").agg({'ConvertedCompYearly':'mean'}).reset_index()
cleaned_India_work_df=cleaned_India_work_df.rename(columns={'ConvertedCompYearly':'India_AvgSalary'})

full_workexp_df=cleaned_India_work_df.merge(cleaned_world_work_df,on=['WorkExp'],how='outer')
full_workexp_df=full_workexp_df.merge(cleaned_USA_work_df,on=['WorkExp'],how='outer')
full_workexp_df

    WorkExp  India_AvgSalary  World_AvgSalary  USA_AvgSalary
0       1.0     11781.669903     34477.447535   79646.816794
1       2.0     10527.110092     40186.856722   85478.398693
2       3.0     19514.543689     50749.624060  102219.461538
3       4.0     16312.642105     51617.594669   99582.324675
4       5.0     28586.553846     65895.522782  128917.671429
..      ...              ...              ...            ...
24     25.0     30355.000000    120431.673426  192154.844828
25     26.0    140650.000000    123892.950192  181967.157895
26     27.0     64707.000000    136063.350746  202396.739130
27     28.0              NaN    132778.334646  214769.863014
28     29.0     31395.000000    143739.070866  213891.681818

[29 rows x 4 columns]

##### Visual

## **Key Insights: Salary vs. Work Experience**

* **The US Market Premium:** The US consistently leads in compensation across all experience levels due to its highly mature tech ecosystem and premium software engineering labor costs.

* **Global Trend Stability:** The 'World' trendline remains incredibly smooth because its massive global sample size completely averages out regional economic extremes.

* **India's High-Experience Volatility**: India’s sharp spikes and dips past 20 years are caused by low sample sizes and extreme outlier sensitivity, a direct byproduct of the country's post-2000s IT boom.

* **The 15-Year Growth Plateau:** Across all regions, aggressive salary growth driven by early-career job-hopping levels off after 15–20 years as developers reach senior management ceilings.

In [10]:
graph_workexp=px.line(
                      full_workexp_df,
                      x='WorkExp',
                      y=['World_AvgSalary','USA_AvgSalary','India_AvgSalary'],
                      title='Salary as work exp increase',
                      template='plotly_dark',
                      labels={'value':'Salary','WorkExp':'WorkExp'},
                      markers=True,
                      color_discrete_sequence=['red','green','blue']
)

graph_workexp.update_layout(xaxis_title='WorkExp',yaxis_title='AvgSalary')
graph_workexp.show()

## Average Salary of Popular Language & Database

### Language

In [11]:
popular_list = [
    'Python', 'JavaScript', 'Java', 'C++', 'C#', 'C', 'TypeScript', 'Go',
    'SQL', 'PHP', 'Swift', 'Kotlin', 'Rust', 'R', 'Ruby', 'MATLAB', 'Dart',
    'PowerShell', 'Visual Basic', 'Julia'
]

c_df=df.dropna(subset=["ConvertedCompYearly"]).copy()
c_df=c_df[(c_df["ConvertedCompYearly"]>0) & (c_df["ConvertedCompYearly"]<1000000)]

exploded_df = c_df.assign(Language=c_df['LanguageHaveWorkedWith'].str.split(';')).explode('Language')

filtered_df = exploded_df[exploded_df['Language'].isin(popular_list)]

Lang_df = filtered_df.groupby('Language')['ConvertedCompYearly'].mean().reset_index()
Lang_df = Lang_df.rename(columns={'ConvertedCompYearly': 'AvgSalary'}).sort_values(by='AvgSalary', ascending=False)

Lang_df

      Language      AvgSalary
13        Ruby  118019.280622
4           Go  110308.862672
16       Swift  107018.877946
14        Rust  106261.303382
7       Kotlin   97482.808933
..         ...            ...
6   JavaScript   90740.466429
12           R   88471.988083
8       MATLAB   76708.397418
9          PHP   73417.582334
3         Dart   72546.881370

[18 rows x 2 columns]

#### Interactive Graph

In [12]:
graph=px.bar(
             Lang_df,
             x='AvgSalary',
             y='Language',
             orientation='h',
             color='AvgSalary',
             color_continuous_scale='viridis',
             title='Average Salary of Popular Language',
             template='plotly_dark'
            )

graph.update_yaxes(categoryorder='total ascending')
graph.update_layout(coloraxis_showscale=False)
graph.show()

### Database

In [13]:
popular_databases = [
    'PostgreSQL', 'MySQL', 'SQLite', 'MongoDB', 'Redis',
    'Microsoft SQL Server', 'Amazon DynamoDB', 'MariaDB',
    'Elasticsearch', 'Firebase Realtime Database','Oracle'
]

database_df=df.dropna(subset=["ConvertedCompYearly","DatabaseHaveWorkedWith"]).copy()
database_df=database_df[(database_df["ConvertedCompYearly"]>0) & (database_df["ConvertedCompYearly"]<1000000)]
database_df=database_df[["DatabaseHaveWorkedWith","ConvertedCompYearly"]]

database_df=database_df.assign(Database=database_df['DatabaseHaveWorkedWith'].str.split(';')).explode('Database')

database_df=database_df[database_df['Database'].isin(popular_databases)]
database_df=database_df.groupby("Database")['ConvertedCompYearly'].mean().reset_index()
database_df=database_df.sort_values(by='ConvertedCompYearly',ascending=False)

database_df

                     Database  ConvertedCompYearly
0               Elasticsearch        105952.398827
8                       Redis        101743.654565
7                  PostgreSQL         95094.910908
9                      SQLite         91143.552381
3        Microsoft SQL Server         89085.439374
6                      Oracle         82561.179279
4                     MongoDB         81458.954095
5                       MySQL         81019.935275
2                     MariaDB         79614.431522
1  Firebase Realtime Database         65950.765568

#### Interactive Graph

In [14]:
graph_db=px.bar(
                database_df,
                x='ConvertedCompYearly',
                y='Database',
                orientation='h',
                color='Database',
                title='Average Salary of Popular Database',
                template='plotly_dark'
              )

graph_db.update_layout(xaxis_title='AvgSalary',coloraxis_showscale=False)
graph_db.show()