<a href="https://colab.research.google.com/github/vikassinngh123/AI-ML-Learning/blob/main/04-Pandas/03_StackOverflow_Survey_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df=pd.read_csv('/content/drive/MyDrive/survey_results_public.csv')
# df=pd.read_[different file type in place of csv]
# pd.set_option('display.max_columns',172)
# pd.set_option('display.max_row',172)
df.head(20)

/tmp/ipykernel_18940/1338741129.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/drive/MyDrive/survey_results_public.csv')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0
6,7,I am a developer by profession,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,Sentry,NaN,ChatGPT;Claude Code;Google Gemini,NaN,When I don’t trust AI’s answers;When I need he...,NaN,6240.0,6.0
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0
9,10,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem;W...,NaN,5400.0,4.0
10,11,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,Spring AI,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Microsoft C...,NaN,When I don’t trust AI’s answers;When I have et...,Code writing. I know this sounds weird but you...,65691.0,10.0
11,12,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,3.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I need qu...,NaN,14400.0,8.0
12,13,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",10.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,1099.0,7.0
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
14,15,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Attending school (full-time);Attending school ...,15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,I don’t think I’ll need help from people anymore,senior development,NaN,9.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
16,17,"I am not primarily a developer, but I write co...",65 years or older,Some college/university study without earning ...,Retired,None of the above,20.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,All the ones that INTELLIGENT programmers curr...,16252.0,NaN
17,18,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,NaN,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I hav...,NaN,NaN,6.0
18,19,I am a developer by profession,35-44 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,20.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,AI will not become more capable in 3-5 years.,NaN,5.0
19,20,"I am not primarily a developer, but I write co...",25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (less than 10 hours per w...,3.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,I don’t think I’ll need help from people anymore,Research,NaN,NaN

In [3]:
df.shape

(49191, 172)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [5]:
df.describe()

,ResponseId,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,...,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,49191.000000,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,...,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,24596.000000,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,...,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,14200.362883,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,...,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,12298.500000,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,...,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,24596.000000,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,...,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,36893.500000,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,...,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,49191.000000,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,...,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [6]:
# pd.set_option('display.max_columns',172)
# pd.set_option('display.max_row',172)

In [7]:
schema_df=pd.read_csv('/content/drive/MyDrive/survey_results_schema.csv')
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [8]:
pd.set_option('display.max_columns',11)
pd.set_option('display.max_row',11)

## Work exp V/s pay

In [9]:
from numpy._core.numeric import full
work_df=df.dropna(subset=["WorkExp","ConvertedCompYearly"])

world_work_df=work_df[(work_df["ConvertedCompYearly"]>=5000) & (work_df["ConvertedCompYearly"]<=800000) & (work_df["WorkExp"]>0) & (work_df["WorkExp"]<=25)]
cleaned_world_work_df=world_work_df[["WorkExp","ConvertedCompYearly"]]
cleaned_world_work_df=cleaned_world_work_df.groupby("WorkExp").agg({'ConvertedCompYearly':'mean'}).reset_index()
cleaned_world_work_df=cleaned_world_work_df.rename(columns={'ConvertedCompYearly':'World_AvgSalary'})

#USA
USA_work_df=work_df[(work_df["ConvertedCompYearly"]>=5000) & (work_df["ConvertedCompYearly"]<=800000) & (work_df["WorkExp"]>0) & (work_df["WorkExp"]<=25) & (work_df['Country'].isin(['United States of America']))]
cleaned_USA_work_df=USA_work_df[["WorkExp","ConvertedCompYearly"]]
cleaned_USA_work_df=cleaned_USA_work_df.groupby("WorkExp").agg({'ConvertedCompYearly':'mean'}).reset_index()
cleaned_USA_work_df=cleaned_USA_work_df.rename(columns={'ConvertedCompYearly':'USA_AvgSalary'})

#India
India_work_df=work_df[(work_df["ConvertedCompYearly"]>=5000) & (work_df["ConvertedCompYearly"]<=100000) & (work_df["WorkExp"]>0) & (work_df["WorkExp"]<=25) & (work_df['Country'].isin(['India']))]
cleaned_India_work_df=India_work_df[["WorkExp","ConvertedCompYearly"]]
cleaned_India_work_df=cleaned_India_work_df.groupby("WorkExp").agg({'ConvertedCompYearly':'mean'}).reset_index()
cleaned_India_work_df=cleaned_India_work_df.rename(columns={'ConvertedCompYearly':'India_AvgSalary'})

full_workexp_df=cleaned_India_work_df.merge(cleaned_world_work_df,on=['WorkExp'],how='outer')
full_workexp_df=full_workexp_df.merge(cleaned_USA_work_df,on=['WorkExp'],how='outer')
full_workexp_df

    WorkExp  India_AvgSalary  World_AvgSalary  USA_AvgSalary
0       1.0     14720.936508     40456.527820   80836.232558
1       2.0     14159.680556     45730.588501   85478.398693
2       3.0     18501.847059     55010.306198   98585.709497
3       4.0     15841.329412     54510.625122   99582.324675
4       5.0     23182.964286     70157.876280  130751.309179
..      ...              ...              ...            ...
20     21.0     46590.250000    128584.235880  192834.352273
21     22.0     71603.800000    136615.116129  200472.864583
22     23.0     58119.666667    120014.814159  178921.338710
23     24.0     41846.000000    128637.109091  186527.083333
24     25.0     35569.200000    121940.228758  189307.030303

[25 rows x 4 columns]

##### Visual

## **Key Insights: Salary vs. Work Experience**

* **The US Market Premium:** The US consistently leads in compensation across all experience levels due to its highly mature tech ecosystem and premium software engineering labor costs.

* **Global Trend Stability:** The 'World' trendline remains incredibly smooth because its massive global sample size completely averages out regional economic extremes.

* **India's High-Experience Volatility**: India’s sharp spikes and dips past 20 years are caused by low sample sizes and extreme outlier sensitivity, a direct byproduct of the country's post-2000s IT boom.

* **The 15-Year Growth Plateau:** Across all regions, aggressive salary growth driven by early-career job-hopping levels off after 15–20 years as developers reach senior management ceilings.

In [10]:
graph_workexp=px.line(
                      full_workexp_df,
                      x='WorkExp',
                      y=['World_AvgSalary','USA_AvgSalary','India_AvgSalary'],
                      title='Salary as work exp increase',
                      template='plotly_dark',
                      labels={'value':'Salary','WorkExp':'WorkExp'},
                      markers=True,
                      color_discrete_sequence=['red','green','blue']
)

graph_workexp.update_layout(xaxis_title='WorkExp',yaxis_title='AvgSalary')
graph_workexp.show()

## Average Salary of Popular Language & Database

### Language

In [11]:
popular_list = [
    'Python', 'JavaScript', 'Java', 'C++', 'C#', 'C', 'TypeScript', 'Go',
    'SQL', 'PHP', 'Swift', 'Kotlin', 'Rust', 'R', 'Ruby', 'MATLAB', 'Dart',
    'PowerShell', 'Visual Basic', 'Julia'
]

c_df=df.dropna(subset=["ConvertedCompYearly"]).copy()
c_df=c_df[(c_df["ConvertedCompYearly"]>=4000) & (c_df["ConvertedCompYearly"]<=800000)]

exploded_df = c_df.assign(Language=c_df['LanguageHaveWorkedWith'].str.split(';')).explode('Language')

filtered_df = exploded_df[exploded_df['Language'].isin(popular_list)]

Lang_df = filtered_df.groupby('Language')['ConvertedCompYearly'].mean().reset_index()
Lang_df = Lang_df.rename(columns={'ConvertedCompYearly': 'AvgSalary'}).sort_values(by='AvgSalary', ascending=False)

Lang_df.head()

   Language      AvgSalary
13     Ruby  123818.686395
4        Go  114884.868487
16    Swift  111720.992914
14     Rust  109449.555518
7    Kotlin  101627.149934

#### Interactive Graph

In [12]:
graph=px.bar(
             Lang_df,
             x='AvgSalary',
             y='Language',
             orientation='h',
             color='AvgSalary',
             color_continuous_scale='viridis',
             title='Average Salary of Popular Language',
             template='plotly_dark'
            )

graph.update_yaxes(categoryorder='total ascending')
graph.update_layout(coloraxis_showscale=False)
graph.show()

## Language Popularity V/s Avgsalary

In [13]:
lang_stats = filtered_df.groupby('Language').agg(
    AvgSalary=('ConvertedCompYearly', 'mean'),
    DeveloperCount=('Language', 'count')
).reset_index()


fig_scatter = px.scatter(
    lang_stats,
    x='DeveloperCount',
    y='AvgSalary',
    text='Language', # Puts the name right next to the dot
    size='DeveloperCount', # Bigger dots for more popular languages
    color='AvgSalary',
    color_continuous_scale='plasma',
    title='Market Dynamics: Language Popularity vs. Average Salary',
    template='plotly_dark'
)


fig_scatter.update_traces(textposition='top center')
fig_scatter.update_layout(coloraxis_showscale=False)
fig_scatter.show()

### Database

In [14]:
popular_databases = [
    'PostgreSQL', 'MySQL', 'SQLite', 'MongoDB', 'Redis',
    'Microsoft SQL Server', 'Amazon DynamoDB', 'MariaDB',
    'Elasticsearch', 'Firebase Realtime Database','Oracle'
]

database_df=df.dropna(subset=["ConvertedCompYearly","DatabaseHaveWorkedWith"]).copy()
database_df=database_df[(database_df["ConvertedCompYearly"]>=5000) & (database_df["ConvertedCompYearly"]<=800000)]
database_df=database_df[["DatabaseHaveWorkedWith","ConvertedCompYearly"]]

database_df=database_df.assign(Database=database_df['DatabaseHaveWorkedWith'].str.split(';')).explode('Database')

database_df=database_df[database_df['Database'].isin(popular_databases)]
database_df=database_df.groupby("Database")['ConvertedCompYearly'].mean().reset_index()
database_df=database_df.sort_values(by='ConvertedCompYearly',ascending=False)

database_df

                     Database  ConvertedCompYearly
0               Elasticsearch        110235.271746
8                       Redis        107473.426622
7                  PostgreSQL        100536.505441
9                      SQLite         96785.825889
3        Microsoft SQL Server         93630.094232
6                      Oracle         88806.861050
4                     MongoDB         88792.661671
5                       MySQL         88032.570717
2                     MariaDB         85071.448121
1  Firebase Realtime Database         76885.855714

#### Interactive Graph

In [15]:
graph_db=px.bar(
                database_df,
                x='ConvertedCompYearly',
                y='Database',
                orientation='h',
                color='Database',
                title='Average Salary of Popular Database',
                template='plotly_dark'
              )

graph_db.update_layout(xaxis_title='AvgSalary',coloraxis_showscale=False)
graph_db.show()

#### Deep Analysis

In [16]:
popular_databases = [
    'PostgreSQL', 'MySQL', 'SQLite', 'MongoDB', 'Redis',
    'Microsoft SQL Server', 'Amazon DynamoDB', 'MariaDB',
    'Elasticsearch', 'Firebase Realtime Database','Oracle'
]

v_database_df=df.dropna(subset=["ConvertedCompYearly","DatabaseHaveWorkedWith"]).copy()
v_database_df=v_database_df[(v_database_df["ConvertedCompYearly"]>=5000) & (v_database_df["ConvertedCompYearly"]<=800000)]
v_database_df=v_database_df.assign(Database=v_database_df['DatabaseHaveWorkedWith'].str.split(';')).explode('Database')

v_database_df=v_database_df[v_database_df['Database'].isin(popular_databases)]
v_database_df=v_database_df[['Database','ConvertedCompYearly','WorkExp']]
v_database_df.head()

     Database  ConvertedCompYearly  WorkExp
0  PostgreSQL              61256.0      8.0
1     MongoDB             104413.0      2.0
2     MongoDB              53061.0     10.0
2       MySQL              53061.0     10.0
2  PostgreSQL              53061.0     10.0

In [17]:
graph_db_violin=px.violin(
                          v_database_df,
                          x='Database',
                          y='ConvertedCompYearly',
                          color='Database',
                          box=True,
                          title='Salary Distribution Across Popular Database',
                          template='plotly_dark'
                        )
graph_db_violin.update_layout(xaxis_title='Database',yaxis_title='Salary',showlegend=False)
graph_db_violin.show()

## EDlevel vs Salary

In [18]:
ed_levels_list = df['EdLevel'].dropna().unique().tolist()
ed_clean_map = {
    "Master’s degree (M.A., M.S., M.Eng., MBA, etc.)": "Master's",
    "Bachelor’s degree (B.A., B.S., B.Eng., etc.)": "Bachelor's",
    "Associate degree (A.A., A.S., etc.)": "Associate",
    "Some college/university study without earning a degree": "Some College",
    "Professional degree (JD, MD, Ph.D, Ed.D, etc.)": "Professional/PhD",
    "Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)": "High School",
    "Primary/elementary school": "Primary",
    "Other (please specify):": "Other"
}

ed_df=df.dropna(subset=["ConvertedCompYearly","EdLevel",'WorkExp']).copy()
ed_df=ed_df[(ed_df["ConvertedCompYearly"] >= 5000) & (ed_df["ConvertedCompYearly"]<=800000) & (ed_df['EdLevel'].isin(ed_levels_list))]
ed_df=ed_df[["EdLevel","ConvertedCompYearly",'WorkExp']]
ed_df['EdLevel']=ed_df['EdLevel'].replace(ed_clean_map)
ed_df.head()

      EdLevel  ConvertedCompYearly  WorkExp
0    Master's              61256.0      8.0
1   Associate             104413.0      2.0
2  Bachelor's              53061.0     10.0
3  Bachelor's              36197.0      4.0
4    Master's              60000.0     21.0

In [19]:
ed_graph=px.violin(ed_df,
                   x='EdLevel',
                   y='ConvertedCompYearly',
                   color='EdLevel',
                   hover_data=['WorkExp'],
                   box=True,
                   title='Salary vs EdLevel',
                   template='plotly_dark'
                   )
ed_graph.update_layout(xaxis_title='EdLevel',yaxis_title='Salary')
ed_graph.show()

## Remote vs. Hybrid vs. On-Site Dynamics

In [20]:

remote_df=df.dropna(subset=["ConvertedCompYearly","RemoteWork"]).copy()
C_remote_df=remote_df[(remote_df["ConvertedCompYearly"]>=5000) & (remote_df["ConvertedCompYearly"]<=800000) & (remote_df['RemoteWork'].str.contains('Remote|Hybrid|In-person|Your choice'))]
remote_df=C_remote_df[["RemoteWork","ConvertedCompYearly"]]
remote_df=remote_df.replace({'RemoteWork': {'Remote': 'Remote', 'Hybrid (some in-person, leans heavy to flexibility)': 'Hybrid_Flexible', 'In-person': 'On-Site','Hybrid (some remote, leans heavy to in-person)':'Hybrid_On-Site','Your choice (very flexible, you can come in when you want or just as needed)':'My choice'}})

remote_df.head()

        RemoteWork  ConvertedCompYearly
0           Remote              61256.0
1  Hybrid_Flexible             104413.0
3           Remote              36197.0
7           Remote              72000.0
8           Remote              70000.0

#### Visuals

In [21]:
graph_remote_violin=px.violin(remote_df,
                              x='RemoteWork',
                              y='ConvertedCompYearly',
                              box=True,
                              title='Salary vs Work_Type',
                              template='plotly_dark',
                              color='RemoteWork'
                            )
graph_remote_violin.update_layout(xaxis_title='Work_Type',yaxis_title='Annual_Salary',showlegend=False)
graph_remote_violin.show()

#### Popularity OF Work_Type

In [22]:
popu_remote_df=remote_df.groupby('RemoteWork').agg(AvgSalary=('ConvertedCompYearly', 'mean'),
                                                   DeveloperCount=('RemoteWork', 'count')).reset_index().copy()


graph_work_scatter=px.scatter(
                              popu_remote_df,
                              x='DeveloperCount',
                              y='AvgSalary',
                              text='RemoteWork',
                              size='DeveloperCount',
                              color='AvgSalary',
                              color_continuous_scale='plasma',
                              title='Market Dynamics: Work_Type Popularity vs. Average Salary',
                              template='plotly_dark'

)
graph_work_scatter.update_traces(textposition='top center')
graph_work_scatter.update_layout(coloraxis_showscale=False)
graph_work_scatter.show()

#### Work Exp Distribution with On_site and Remote

In [23]:
remote_onsite_df=C_remote_df[['RemoteWork','WorkExp']]
remote_onsite_df=remote_onsite_df[(remote_onsite_df['RemoteWork'].str.contains('Remote|In-person')) & (remote_onsite_df['WorkExp']<=30) & (remote_onsite_df['WorkExp']>0)]

graph_exp_type=px.violin(
                         remote_onsite_df,
                         x='RemoteWork',
                         y='WorkExp',
                         box=True,
                         title='Distribution of : WorkExp vs Work_Type',
                         template='plotly_dark',
                         color='RemoteWork'
)
graph_exp_type.update_layout(xaxis_title='Work_Type',yaxis_title='WorkExp')
graph_exp_type.show()